name: Pydio
services:
  cells:
    image: pydio/cells:latest
    container_name: pydio-cells
    restart: unless-stopped
    init: true
    ports: ["8080:8080"]
    environment:
      CELLS_EXTERNAL: "https://pydio.sakul-flee.de"
    volumes:
      - pydio-cells:/var/cells
      - pydio-data:/var/cells/data
    networks:
      - caddy_caddy
      - pydio

  mysql:
    image: mysql:9
    container_name: pydio-mysql
    restart: unless-stopped
    init: true
    environment:
      MYSQL_ROOT_PASSWORD: EethePah1ohy2Ich6ahyaitona6oe4ohyai1joerohb7Hae7eelaipienohriev8
      MYSQL_DATABASE: cells
      MYSQL_USER: pydio
      MYSQL_PASSWORD: jei8vae0iehai9gaSho5chae8EeGeiph4ethei7Fael8xied1arekaiqu3eefeew
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    volumes:
      - pydio-mysql:/var/lib/mysql
    networks:
      - pydio

volumes:
  pydio-data: {}
  pydio-cells: {}
  pydio-mysql: {}

networks:
  pydio:
  caddy_caddy:
    external: true
