services:
  pia:
    image: j0ner/pia-wireguard
    container_name: vpn_pia
    restart: unless-stopped
    environment:
      - PIA_USER=p8130229
      - PIA_PASS=oht8nFZEhp#^CPEF%SWaZz
      - PIA_REGION_ID=swiss
      - VPN_IP_CHECK_DELAY=5
      - VPN_LAN_NETWORKS=192.168.178.0/24
    volumes:
      - pia:/config
    cap_add:
      - NET_ADMIN
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1

volumes:
  pia:
