name: Hello World
services:
    mc-server:
        stdin_open: true
        tty: true
        image: eclipse-temurin:21
        volumes:
            -  $HOME/Data/MCServer:/app
        command:
            - java
            - -jar
            - /app/server.jar
