- name: "Cloudflare-DDNS"
  hosts: cloudflare-ddns
  roles:
    - role: podman
    - role: cloudflare-ddns

- name: "Caddy"
  hosts: caddy
  roles:
    - role: podman
    - role: caddy

- name: "Syncthing"
  hosts: syncthing
  roles:
    - role: podman
    - role: syncthing

- name: "Minecraft"
  hosts: minecraft
  roles:
    - role: podman
    - role: minecraft

- name: "Matrix"
  hosts: matrix
  roles:
    - role: podman
    - role: matrix

- name: "Technitium-DNS"
  hosts: technitium-dns
  roles:
    - role: podman
    - role: technitium-dns

- name: "Pixelmon"
  hosts: pixelmon
  roles:
    - role: podman
    - role: pixelmon
