name: Cloudflare-DDNS
services:
  cloudflare_ddns:
    image: ghcr.io/sakulflee/cloudflare-ddns:latest
    restart: on-failure
    stdin_open: true
    tty: true
    init: true
    volumes:
      - $HOME/Data/CloudFlare-DDNS:/opt/cf_ddns:z
