name: Cloudflare-DDNS
services:
  cloudflare_ddns:
    image: ghcr.io/sakulflee/cloudflare-ddns:alpine-3.21
    restart: on-failure
    stdin_open: true
    tty: true
    volumes:
      - ${HOME}/Data/CloudFlare-DDNS:/opt/cf_ddns
