name: Cloudflare-DDNS
services:
  cloudflare_ddns:
    image: ghcr.io/sakul6499/cloudflare_ddns:latest
    restart: on-failure
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: $HOME/Data/CloudFlare-DDNS/ipv4.last'
        target: /opt/cf_ddns/ipv4.last
      - type: bind
        source: $HOME/Data/CloudFlare-DDNS/ipv6.last
        target: /opt/cf_ddns/ipv6.last
      - type: bind
        source: $HOME/Data/CloudFlare-DDNS/settings
        target: /opt/cf_ddns/settings
