apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: traefik-websecure-redirect 
  namespace: traefik
dependsOn:
- cert-manager-cluster-issuer
resources:
- middleware-redirect-to-websecure.yaml
