---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scraper-config
  namespace: media
data:
  config.toml: |-
    [account]
      auth_token = "ODUyNzYxMDEyMDExNTYwOTYwOjE6MjowOTZmODEyZGE2ZDY2NGM3MzA4NDJhZDQwMmVkYmE"
      user_agent = "Mozilla/5.0 (Macintosh; Linux x86_64; ZorinOS) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.7499.110 Safari/537.36 Zorin/18 Brave/1.85.116"
    [options]
      save_location = "/mnt/media/fansly"
      m3u8_dl = false
      check_updates = false
      skip_previews = true
      use_content_as_filename = false
      content_filename_template = "{date}-{content}_{index}"
      content_filename_length = 50
      date_format = "20060102"
      download_media_type = "all"
      skip_downloaded_posts = false
      download_profile_pic = true
      post_limit = 0
    [live_settings]
      save_location = ""
      vods_file_extension = ".ts"
      ffmpeg_convert = true
      generate_contact_sheet = true
      use_mt_for_contact_sheet = false
      filename_template = "{model_username}_{date}_{streamId}_{streamVersion}"
      date_format = "20060102_150405"
      record_chat = true
      ffmpeg_recording_options = ""
      ffmpeg_conversion_options = ""
      check_interval = 60
    [notifications]
      enabled = false
      system_notify = true
      discord_webhook = ""
      discord_mention_id = ""
      telegram_bot_token = ""
      telegram_chat_id = ""
      notify_on_live_start = true
      notify_on_live_end = false
      send_contact_sheet_on_live_end = false
    [security_headers]
      device_id = "864785549938946049"
      session_id = "852761012011560960"
      check_key = "necvac-govry3-tybkYz"
      last_updated = 2026-01-06T04:55:00.863451499Z
