---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: fscraper
  namespace: media
resources:
  - configmap.yaml
  - deployment-msvr.yaml
  - deployment-cmvr.yaml
  - deployment-kai.yaml
  - deployment-lin.yaml
  - deployment-nuk.yaml
