apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: cert-manager
resources:
  - namespace.yaml
  - helm-repository.yaml
  - helm-release.yaml
  - cluster-issuer-letsencrypt-production.yaml
  - cluster-issuer-letsencrypt-staging.yaml
  - cluster-issuer-zerossl.yaml
