apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: cert-manager
dependsOn:
- metallb
resources:
- namespace.yaml
- helm-repository.yaml
- helm-release.yaml                          
