apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: media
  namespace: media
resources:
  - namespace.yaml
  - persistent-volume-claim.yaml
  - helm-repository-alekc.yaml
  - helm-release-sonarr.yaml
  - helm-release-radarr.yaml
  - helm-release-prowlarr.yaml
  - helm-release-jellyfin.yaml
  - qbittorrent-vpn/
  # - fscraper/
