apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: media
  namespace: longhorn-system
dependsOn:
- longhorn
- cert-manager
- cloudflare-ddns
- traefik
resources:
- namespace.yaml
- persistent-volume-claim.yaml
- helm-repository.yaml
- helm-release-sonarr.yaml
