---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: davmail
  namespace: davmail
  labels:
    app: davmail
spec:
  selector:
    matchLabels:
      app: davmail
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: davmail
    spec:
      volumes:
        - name: davmail-config
          persistentVolumeClaim:
            claimName: davmail-config
      containers:
        - name: davmail
          image: jberrenberg/davmail:6.3.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: davmail-config
              mountPath: /etc/davmail
