---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: davmail
  namespace: davmail
resources:
  - namespace.yaml
  - persistent-volume-claim.yaml
  - deployment.yaml
  - service.yaml
