- name: Import network tasks
  ansible.builtin.import_tasks:
    file: network.yml

- name: Import Database tasks
  ansible.builtin.import_tasks:
    file: database.yml

- name: Import Synapse tasks
  ansible.builtin.import_tasks:
    file: synapse.yml
