- name: Import network tasks
  ansible.builtin.import_tasks:
    file: network.yml

- name: Import Postgres tasks
  ansible.builtin.import_tasks:
    file: postgres.yml

- name: Import Synapse tasks
  ansible.builtin.import_tasks:
    file: synapse.yml
