apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: longhorn 
  namespace: longhorn
dependsOn:
- cert-manager-cluster-issuer
resources:
- namespace.yaml
- helm-repository.yaml
- helm-release.yaml
