apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: longhorn 
  namespace: longhorn-system
dependsOn:
- cert-manager-cluster-issuer
resources:
- namespace.yaml
- helm-repository.yaml
- helm-release.yaml
- middleware-auth.yaml
- ingress.yaml
- backup-target-setting.yaml
