apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager-cluster-issuer 
  namespace: cert-manager
dependsOn:
- cert-manager
resources:
- namespace.yaml
# - pvc-cache.yaml
# - pvc-ipv4.yaml
# - cronjob.yaml
