apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cloudflare-ddns
  namespace: cloudflare-ddns
resources:
- namespace.yaml
- pvc-cache.yaml
- pvc-ipv4.yaml
- cronjob.yaml
