apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cert-manager-cluster-issuer 
  namespace: cert-manager
dependsOn:
- cert-manager
resources:
- secret-zerossl-eab.yaml
- cluster-issuer-letsencrypt-production.yaml  
- cluster-issuer-letsencrypt-staging.yaml     
- cluster-issuer-zerossl.yaml                 
