apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: ceph 
  namespace: ceph
resources:
- namespace.yaml
- helm-repository.yaml
- helm-release.yaml
- middleware-auth.yaml
- ingress.yaml
- backup-target.yaml
