apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: rook-ceph
  namespace: rook-ceph
resources:
- namespace.yaml
- helm-repository.yaml
- helm-release-rook-ceph.yaml
- helm-release-rook-ceph-cluster.yaml
