apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-casc
  namespace: jenkins
data:
  1-authorization-strategy.yaml: |
    jenkins:
      authorizationStrategy:
        globalMatrix:
          entries:
            - user:
                name: "anonymous"
                permissions:
                  - "Overall/Read"
                  - "Job/Read"
            - group:
                name: "authenticated"
                permissions:
                  - "Overall/Administer"
  2-locale.yaml: |
    appearance:
      locale:
        allowUserPreferences: true
        ignoreAcceptLanguage: false
        systemLocale: "en"
