apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: jenkins
  namespace: jenkins
dependsOn:
- cert-manager-cluster-issuer
- traefik
resources:
- namespace.yaml
- helm-repository-jenkins-operator.yaml
- helm-release-jenkins-operator.yaml
- jenkins-instance.yaml
