- name: Install podman
  ansible.builtin.package:
    name: podman
    state: present

- name: Enable and start podman service
  ansible.builtin.service:
    name: podman
    enabled: true
    state: started

- name: Enable and start cgroups service
  ansible.builtin.service:
    name: cgroups
    enabled: true
    state: started
