apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: cloud-native-pg  
  namespace: cloud-native-pg
resources:
- namespace.yaml
- helm-repository.yaml
- helm-release.yaml
