apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: media-qbittorrent
  namespace: media
dependsOn:
- longhorn
- cert-manager
- cloudflare-ddns
- traefik
resources:
- deployment.yaml
- ingress.yaml
- persistent-volume-claim.yaml
- service.yaml
