apiVersion: v1
kind: Service
metadata:
  name: qbittorrent-vpn-svc
  namespace: media
spec:
  type: ClusterIP
  selector:
    app: qbittorrent-vpn
  ports:
    - name: http
      port: 8080
      targetPort: 8080
