apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- secrets-repository.yaml
- secrets-kustomization.yaml 
- flux-repository.yaml
- flux-kustomization.yaml
