apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tuwunel
  namespace: matrix
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`matrix.sakul-flee.de`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: tuwunel
          port: 6167
  tls:
    secretName: matrix-sakul-flee-de-tls
