apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: tuwunel
  namespace: matrix
resources:
  - certificate.yaml
  - deployment.yaml
  - ingress-route.yaml
  - persistent-volume-claim.yaml
  - service.yaml
