apiVersion: v1
kind: Service
metadata:
  name: tuwunel
  namespace: matrix
spec:
  type: LoadBalancer
  selector:
    app: tuwunel
  ports:
    - name: tuwunel
      port: 6167
      targetPort: 6167
    - name: tuwunel-federation
      port: 8448
      targetPort: 8448
