apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: hytale
  namespace: hytale
resources:
  - namespace.yaml
  - helm-repository.yaml
  - helm-release.yaml
  - service-account.yaml
  - role.yaml
  - role-binding.yaml
  - cronjob-restarter.yaml
