apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: forgejo
  namespace: forgejo
dependsOn:
- cert-manager-cluster-issuer
- traefik
- redis
resources:
- namespace.yaml
- database-postgres.yaml
- helm-repository-redis.yaml
- helm-repository.yaml
- helm-release-redis.yaml
- helm-release.yaml
