apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus 
  namespace: flux-system
spec:
  interval: 30m0s
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system 
  targetNamespace: kube-prometheus
  timeout: 3m0s
  wait: true
  path: ./apps/kube-prometheus/
