apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cert-manager.yaml
- cert-manager-cluster-issuer.yaml
- cloudflare-ddns.yaml
- metallb.yaml
- traefik.yaml
- longhorn.yaml
- longhorn-config.yaml
- cloudnative-pg.yaml
- pgadmin.yaml
- nextcloud.yaml
