apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: csi-s3
  namespace: csi-s3
resources:
  - namespace.yaml
  - helm-repository.yaml
  - helm-release.yaml
  - service.yaml
  - endpoints.yaml
